# Site settings
encoding: utf-8
exclude: ['node_modules']

title: Up.front
email: mail@kristinaschneider.com
description: > # this means to ignore newlines until "baseurl:"
  "Up.front – Meetup for the sustainability and tech Berlin"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cleanweb.berlin" # the base hostname & protocol for your site
twitter_username: cleanwebberlin
facebook_username:  cleanwebberlin

# permalink: pretty

sass:
    style: compressed

future: true

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      time: 8:00pm
      layout: post
